/** Source OpenAPI `/api/v1` operations. Do not invent alternate verbs. */
export const ApiV1Endpoints = {
  LOGIN: '/api/v1/auth/login',
  LOGOUT: '/api/v1/auth/logout',
  REFRESH: '/api/v1/auth/refresh',
  AUTH_ME: '/api/v1/auth/me',
  AUTH_FORGOT_PASSWORD: '/api/v1/auth/forgot-password',
  AUTH_RESET_VERIFY: '/api/v1/auth/forgot-password/verify',
  AUTH_RESET_RESEND: '/api/v1/auth/forgot-password/resend',
  AUTH_RESET_PASSWORD: '/api/v1/auth/forgot-password/reset',
  AUTH_CHANGE_PASSWORD: '/api/v1/auth/change-password',
  AUTH_PROFILE_AVATAR: '/api/v1/auth/profile/avatar',
  ORGANIZATIONS: '/api/v1/organizations',
  BRANCHES: (organizationId: number) => `/api/v1/organizations/${organizationId}/branches`,
  USERS: '/api/v1/users',
  ROLE_ASSIGNMENTS: (userId: number) => `/api/v1/users/${userId}/role-assignments`,
  QUOTATIONS: '/api/v1/quotations',
  QUOTATION_REVISIONS: (quotationId: number | string) => `/api/v1/quotations/${quotationId}/revisions`,
  QUOTATION_SEND: (revisionId: number | string) => `/api/v1/quotation-revisions/${revisionId}/send`,
  QUOTATION_ACCEPT: (revisionId: number | string) => `/api/v1/quotation-revisions/${revisionId}/accept`,
  QUOTATION_SUBMIT: (revisionId: number | string) => `/api/v1/quotation-revisions/${revisionId}/submit`,
  QUOTATION_CONVERT: (revisionId: number | string) => `/api/v1/quotation-revisions/${revisionId}/convert`,
  SERVICE_ORDERS: '/api/v1/service-orders',
  SERVICE_ORDER: (id: number | string) => `/api/v1/service-orders/${id}`,
  SERVICE_ORDER_CONTAINERS: (id: number | string) => `/api/v1/service-orders/${id}/containers`,
  SERVICE_ORDER_COMPONENTS: (id: number | string) => `/api/v1/service-orders/${id}/components`,
  COMPONENT: (id: number | string) => `/api/v1/service-order-components/${id}`,
  COMPONENT_VALUES: (id: number | string) => `/api/v1/service-order-components/${id}/values`,
  COMPONENT_COMPLETE: (id: number | string) => `/api/v1/service-order-components/${id}/complete`,
  SERVICE_ORDER_CHARGES: (id: number | string) => `/api/v1/service-orders/${id}/charges`,
  SERVICE_ORDER_DYNAMIC_TABS: (id: number | string) => `/api/v1/service-orders/${id}/dynamic-tabs`,
  SERVICE_ORDER_DYNAMIC_ROWS: (id: number | string, tabId: number | string) =>
    `/api/v1/service-orders/${id}/dynamic-tabs/${tabId}/rows`,
  SERVICE_ORDER_DYNAMIC_ROW: (id: number | string, tabId: number | string, rowId: number | string) =>
    `/api/v1/service-orders/${id}/dynamic-tabs/${tabId}/rows/${rowId}`,
  SERVICE_ORDER_DYNAMIC_ROWS_BULK: (id: number | string, tabId: number | string) =>
    `/api/v1/service-orders/${id}/dynamic-tabs/${tabId}/rows/bulk`,
  SERVICE_ORDER_TABS: '/api/v1/service-order-tabs',
  SERVICE_ORDER_TAB: (id: number | string) => `/api/v1/service-order-tabs/${id}`,
  SERVICE_ORDER_TAB_COLUMNS: (tabId: number | string) => `/api/v1/service-order-tabs/${tabId}/columns`,
  SERVICE_ORDER_TAB_COLUMNS_REORDER: (tabId: number | string) => `/api/v1/service-order-tabs/${tabId}/columns/reorder`,
  SERVICE_ORDER_COLUMN: (id: number | string) => `/api/v1/service-order-columns/${id}`,
  SERVICE_CHARGES: '/api/v1/service-charges',
  CHARGE_ISSUE: (id: number | string) => `/api/v1/service-charges/${id}/issue`,
  CHARGE_CREATE_INVOICE: (id: number | string) => `/api/v1/service-charges/${id}/create-finance-invoice`,
  FINANCIAL_DOCUMENTS: '/api/v1/financial-documents',
  FINANCIAL_POST: (id: number | string) => `/api/v1/financial-documents/${id}/post`,
  FINANCIAL_ALLOCATE: (id: number | string) => `/api/v1/financial-documents/${id}/allocate`,
  FINANCIAL_REVERSE: (id: number | string) => `/api/v1/financial-documents/${id}/reverse`,
  JOURNALS: '/api/v1/journal-entries',
  JOURNAL_POST: (id: number | string) => `/api/v1/journal-entries/${id}/post`,
  PERIOD_CLOSE: (id: number | string) => `/api/v1/accounting-periods/${id}/close`,
  ATTACHMENTS_PRESIGN: '/api/v1/attachments/presign',
  ATTACHMENTS: '/api/v1/attachments',
  UI_SCHEMA: (page: string) => `/api/v1/ui-schemas/${encodeURIComponent(page)}`,
  AUDIT_EVENTS: '/api/v1/audit-events',
} as const
