/** Source OpenAPI `/api/v1` operations. Do not invent alternate verbs. */
export const ApiV1Endpoints = {
  SETUP_STATUS: '/api/v1/setup/status',
  SETUP_INITIALIZE: '/api/v1/setup/initialize',
  LOGIN: '/api/v1/auth/login',
  LOGOUT: '/api/v1/auth/logout',
  REFRESH: '/api/v1/auth/refresh',
  AUTH_ME: '/api/v1/auth/me',
  AUTH_FORGOT_PASSWORD: '/api/v1/auth/forgot-password',
  AUTH_RESET_VERIFY: '/api/v1/auth/forgot-password/verify',
  AUTH_RESET_RESEND: '/api/v1/auth/forgot-password/resend',
  AUTH_RESET_PASSWORD: '/api/v1/auth/forgot-password/reset',
  AUTH_CHANGE_PASSWORD: '/api/v1/auth/change-password',
  AUTH_PROFILE_AVATAR: '/api/v1/auth/profile/avatar',
  USERS: '/api/v1/users',
  ROLE_ASSIGNMENTS: (userId: number) => `/api/v1/users/${userId}/role-assignments`,
  QUOTATIONS: '/api/v1/quotations',
  QUOTATION_REVISIONS: (quotationId: number | string) => `/api/v1/quotations/${quotationId}/revisions`,
  QUOTATION_SEND: (revisionId: number | string) => `/api/v1/quotation-revisions/${revisionId}/send`,
  QUOTATION_ACCEPT: (revisionId: number | string) => `/api/v1/quotation-revisions/${revisionId}/accept`,
  QUOTATION_SUBMIT: (revisionId: number | string) => `/api/v1/quotation-revisions/${revisionId}/submit`,
  QUOTATION_CONVERT: (revisionId: number | string) => `/api/v1/quotation-revisions/${revisionId}/convert`,
  SERVICE_ORDERS: '/api/v1/service-orders',
  SERVICE_ORDER: (id: number | string) => `/api/v1/service-orders/${id}`,
  SERVICE_ORDER_FINISH: (id: number | string) => `/api/v1/service-orders/${id}/finish`,
  SERVICE_ORDER_CONTAINERS: (id: number | string) => `/api/v1/service-orders/${id}/containers`,
  SERVICE_ORDER_COMPONENT_TABS: (id: number | string) => `/api/v1/service-orders/${id}/component-tabs`,
  SERVICE_ORDER_COMPONENT_GROUP_ROWS: (id: number | string, groupId: number | string) =>
    `/api/v1/service-orders/${id}/component-tabs/groups/${groupId}/rows`,
  SERVICE_ORDER_COMPONENT_GROUP_ROWS_BULK: (id: number | string, groupId: number | string) =>
    `/api/v1/service-orders/${id}/component-tabs/groups/${groupId}/rows/bulk`,
  COMPONENT_ATTRIBUTES: '/api/v1/component-attributes',
  COMPONENT_ATTRIBUTE: (id: number | string) => `/api/v1/component-attributes/${id}`,
  COMPONENT_GROUPS: '/api/v1/component-groups',
  COMPONENT_GROUP: (id: number | string) => `/api/v1/component-groups/${id}`,
  COMPONENT_GROUP_ATTRIBUTES: (id: number | string) => `/api/v1/component-groups/${id}/attributes`,
  COMPONENT_GROUP_ATTRIBUTES_REORDER: (id: number | string) => `/api/v1/component-groups/${id}/attributes/reorder`,
  COMPONENT_GROUP_ATTRIBUTE: (id: number | string) => `/api/v1/component-group-attributes/${id}`,
  COMPONENT_TABS: '/api/v1/component-tabs',
  COMPONENT_TAB: (id: number | string) => `/api/v1/component-tabs/${id}`,
  COMPONENT_TAB_GROUPS: (id: number | string) => `/api/v1/component-tabs/${id}/groups`,
  COMPONENT_TAB_GROUPS_REORDER: (id: number | string) => `/api/v1/component-tabs/${id}/groups/reorder`,
  COMPONENT_TAB_TRADE_DIRECTIONS: (id: number | string) => `/api/v1/component-tabs/${id}/trade-directions`,
  COMPONENT_TAB_GROUP: (id: number | string) => `/api/v1/component-tab-groups/${id}`,
  COMPONENT_CONFIG_TYPES: '/api/v1/component-tabs/meta/types',
  SERVICE_ORDER_CHARGES: (id: number | string) => `/api/v1/service-orders/${id}/charges`,
  SERVICE_ORDER_INVOICE: (id: number | string) => `/api/v1/service-orders/${id}/invoice`,
  SERVICE_CHARGES: '/api/v1/service-charges',
  CHARGE_ISSUE: (id: number | string) => `/api/v1/service-charges/${id}/issue`,
  CHARGE_CREATE_INVOICE: (id: number | string) => `/api/v1/service-charges/${id}/create-finance-invoice`,
  FINANCIAL_DOCUMENTS: '/api/v1/financial-documents',
  FINANCIAL_POST: (id: number | string) => `/api/v1/financial-documents/${id}/post`,
  FINANCIAL_ALLOCATE: (id: number | string) => `/api/v1/financial-documents/${id}/allocate`,
  FINANCIAL_REVERSE: (id: number | string) => `/api/v1/financial-documents/${id}/reverse`,
  JOURNALS: '/api/v1/journal-entries',
  JOURNAL_POST: (id: number | string) => `/api/v1/journal-entries/${id}/post`,
  PERIOD_CLOSE: (id: number | string) => `/api/v1/accounting-periods/${id}/close`,
  ATTACHMENTS_PRESIGN: '/api/v1/attachments/presign',
  ATTACHMENTS: '/api/v1/attachments',
  UI_SCHEMA: (page: string) => `/api/v1/ui-schemas/${encodeURIComponent(page)}`,
  AUDIT_EVENTS: '/api/v1/audit-events',
  ARCHIVE: '/api/v1/archive',
  ARCHIVE_OPTIONS: '/api/v1/archive/options',
  ARCHIVE_RECORD: (entityType: string, entityId: number | string) =>
    `/api/v1/archive/${encodeURIComponent(entityType)}/${entityId}`,
  ARCHIVE_RESTORE: (entityType: string, entityId: number | string) =>
    `/api/v1/archive/${encodeURIComponent(entityType)}/${entityId}/restore`,
  REPORTS_DASHBOARD: '/api/v1/reports/dashboard',
  REPORTS_RECEIVABLES: '/api/v1/reports/receivables',
  REPORTS_PAYABLES: '/api/v1/reports/payables',
  REPORTS_PROFITABILITY: '/api/v1/reports/profitability',
} as const
