/**
 * Pending change set reported by `AppSaveGrid`, in display order. The parent
 * owns the API calls; the grid only reports what was added, edited, moved or
 * removed.
 */
export type Row = Record<string, unknown>

export interface SaveGridChange {
  /** Rows in their new display order, new rows included. */
  rows: Row[]
  /** Saved row ids that disappeared from the grid. */
  removedIds: string[]
  /** Rows with no server id yet. */
  added: Row[]
}

/**
 * Client ids are prefixed so the grid can tell a new row from a saved one
 * without asking the parent. Generated by `createClientId(SAVE_GRID_NEW_PREFIX)`.
 */
export const SAVE_GRID_NEW_PREFIX = 'new_'

export function isSaveGridNewRow(row: Row) {
  const id = String(row.id ?? '')
  return !id || id.startsWith(SAVE_GRID_NEW_PREFIX)
}