"""initial schema

Revision ID: 140cae56fc24
Revises: 
Create Date: 2026-09-15 13:55:36.305965

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '140cae56fc24'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_parties',
    sa.Column('party_code', sa.String(length=50), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('vat_tin', sa.String(length=64), nullable=True),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_parties')),
    sa.UniqueConstraint('party_code', name=op.f('uq_business_parties_party_code')),
    sa.UniqueConstraint('vat_tin', name=op.f('uq_business_parties_vat_tin'))
    )
    op.create_table('component_groups',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('show_on_job_workspace', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_component_groups')),
    sa.UniqueConstraint('code', name=op.f('uq_component_groups_code'))
    )
    op.create_table('component_templates',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_repeatable', sa.Boolean(), nullable=False),
    sa.Column('instance_mode', sa.String(length=20), nullable=False),
    sa.Column('minimum_instances', sa.Integer(), nullable=True),
    sa.Column('maximum_instances', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_component_templates')),
    sa.UniqueConstraint('code', 'version', name='uq_component_templates_code_version')
    )
    op.create_table('container_types',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('container_size', sa.String(length=32), nullable=True),
    sa.Column('container_kind', sa.String(length=32), nullable=True),
    sa.Column('iso_code', sa.String(length=16), nullable=True),
    sa.Column('length_feet', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('width_millimeter', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('height_millimeter', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('max_gross_weight_kg', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_container_types')),
    sa.UniqueConstraint('code', name=op.f('uq_container_types_code'))
    )
    op.create_table('fee_types',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fee_types')),
    sa.UniqueConstraint('code', name=op.f('uq_fee_types_code'))
    )
    op.create_table('organizations',
    sa.Column('organization_code', sa.String(length=50), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('vat_tin', sa.String(length=64), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('default_currency_code', sa.String(length=3), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('organization_code', name=op.f('uq_organizations_organization_code'))
    )
    op.create_table('permissions',
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('resource', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('code', name=op.f('uq_permissions_code'))
    )
    op.create_table('places',
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('place_category', sa.String(length=64), nullable=False),
    sa.Column('parent_place_id', sa.BigInteger(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_place_id'], ['places.id'], name=op.f('fk_places_parent_place_id_places')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_places')),
    sa.UniqueConstraint('code', name=op.f('uq_places_code'))
    )
    op.create_table('roles',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system_role', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('code', name=op.f('uq_roles_code'))
    )
    op.create_table('trade_directions',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trade_directions')),
    sa.UniqueConstraint('code', name=op.f('uq_trade_directions_code'))
    )
    op.create_table('transport_types',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transport_types')),
    sa.UniqueConstraint('code', name=op.f('uq_transport_types_code'))
    )
    op.create_table('users',
    sa.Column('user_code', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('user_code', name=op.f('uq_users_user_code')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('accounting_periods',
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('closed_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['closed_by_user_id'], ['users.id'], name=op.f('fk_accounting_periods_closed_by_user_id_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_accounting_periods_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounting_periods')),
    sa.UniqueConstraint('organization_id', 'period_year', 'period_month', name='uq_periods_org_year_month')
    )
    op.create_index(op.f('ix_accounting_periods_organization_id'), 'accounting_periods', ['organization_id'], unique=False)
    op.create_index(op.f('ix_accounting_periods_status'), 'accounting_periods', ['status'], unique=False)
    op.create_table('attachments',
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('branch_id', sa.BigInteger(), nullable=True),
    sa.Column('file_name', sa.String(length=512), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('storage_provider', sa.String(length=32), nullable=False),
    sa.Column('document_version', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_attachments_organization_id_organizations')),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], name=op.f('fk_attachments_uploaded_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachments')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_attachments_storage_key'))
    )
    op.create_index(op.f('ix_attachments_organization_id'), 'attachments', ['organization_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('organization_id', sa.BigInteger(), nullable=True),
    sa.Column('branch_id', sa.BigInteger(), nullable=True),
    sa.Column('actor_user_id', sa.BigInteger(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('before_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('after_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_events_actor_user_id_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_audit_events_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_type'), 'audit_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_organization_id'), 'audit_events', ['organization_id'], unique=False)
    op.create_table('branches',
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('branch_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('place_id', sa.BigInteger(), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_head_office', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_branches_organization_id_organizations')),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_branches_place_id_places')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_branches')),
    sa.UniqueConstraint('organization_id', 'branch_code', name='uq_branches_org_code')
    )
    op.create_index(op.f('ix_branches_organization_id'), 'branches', ['organization_id'], unique=False)
    op.create_table('chart_of_accounts',
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('account_code', sa.String(length=32), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('parent_account_id', sa.BigInteger(), nullable=True),
    sa.Column('normal_balance', sa.String(length=10), nullable=False),
    sa.Column('is_postable', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_chart_of_accounts_organization_id_organizations')),
    sa.ForeignKeyConstraint(['parent_account_id'], ['chart_of_accounts.id'], name=op.f('fk_chart_of_accounts_parent_account_id_chart_of_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chart_of_accounts')),
    sa.UniqueConstraint('organization_id', 'account_code', name='uq_coa_org_code')
    )
    op.create_index(op.f('ix_chart_of_accounts_organization_id'), 'chart_of_accounts', ['organization_id'], unique=False)
    op.create_table('customer_customs_accounts',
    sa.Column('party_id', sa.BigInteger(), nullable=False),
    sa.Column('system_name', sa.String(length=128), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_secret_reference', sa.String(length=255), nullable=True),
    sa.Column('encrypted_password', sa.LargeBinary(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['business_parties.id'], name=op.f('fk_customer_customs_accounts_party_id_business_parties'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_customs_accounts'))
    )
    op.create_table('document_sequences',
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('document_type', sa.String(length=64), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('last_value', sa.BigInteger(), nullable=False),
    sa.Column('padding_length', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_document_sequences_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_sequences')),
    sa.UniqueConstraint('organization_id', 'document_type', 'period_year', name='uq_sequences_org_type_year')
    )
    op.create_index(op.f('ix_document_sequences_organization_id'), 'document_sequences', ['organization_id'], unique=False)
    op.create_table('module_records',
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('branch_id', sa.BigInteger(), nullable=True),
    sa.Column('collection', sa.String(length=64), nullable=False),
    sa.Column('record_no', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_module_records_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_module_records'))
    )
    op.create_index(op.f('ix_module_records_branch_id'), 'module_records', ['branch_id'], unique=False)
    op.create_index(op.f('ix_module_records_collection'), 'module_records', ['collection'], unique=False)
    op.create_index(op.f('ix_module_records_organization_id'), 'module_records', ['organization_id'], unique=False)
    op.create_table('party_places',
    sa.Column('party_id', sa.BigInteger(), nullable=False),
    sa.Column('place_id', sa.BigInteger(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['business_parties.id'], name=op.f('fk_party_places_party_id_business_parties'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_party_places_place_id_places')),
    sa.PrimaryKeyConstraint('party_id', 'place_id', 'relationship_type', name=op.f('pk_party_places'))
    )
    op.create_table('party_roles',
    sa.Column('party_id', sa.BigInteger(), nullable=False),
    sa.Column('role_type', sa.String(length=50), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['business_parties.id'], name=op.f('fk_party_roles_party_id_business_parties'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('party_id', 'role_type', name=op.f('pk_party_roles'))
    )
    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('code_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_reset_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_tokens'))
    )
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('quotations',
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('branch_id', sa.BigInteger(), nullable=False),
    sa.Column('quotation_no', sa.String(length=50), nullable=False),
    sa.Column('customer_party_id', sa.BigInteger(), nullable=False),
    sa.Column('trade_direction_id', sa.BigInteger(), nullable=False),
    sa.Column('current_revision_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_party_id'], ['business_parties.id'], name=op.f('fk_quotations_customer_party_id_business_parties')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_quotations_organization_id_organizations')),
    sa.ForeignKeyConstraint(['trade_direction_id'], ['trade_directions.id'], name=op.f('fk_quotations_trade_direction_id_trade_directions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quotations')),
    sa.UniqueConstraint('organization_id', 'quotation_no', name='uq_quotations_org_no')
    )
    op.create_index(op.f('ix_quotations_organization_id'), 'quotations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_quotations_status'), 'quotations', ['status'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('permission_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('template_attributes',
    sa.Column('template_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('data_type', sa.String(length=32), nullable=False),
    sa.Column('input_type', sa.String(length=32), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_repeatable', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('validation_rules', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('reference_type', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['component_templates.id'], name=op.f('fk_template_attributes_template_id_component_templates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_template_attributes')),
    sa.UniqueConstraint('template_id', 'code', name='uq_template_attributes_template_code')
    )
    op.create_table('trade_direction_components',
    sa.Column('trade_direction_id', sa.BigInteger(), nullable=False),
    sa.Column('component_group_id', sa.BigInteger(), nullable=False),
    sa.Column('component_template_id', sa.BigInteger(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_repeatable', sa.Boolean(), nullable=False),
    sa.Column('instance_mode_override', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['component_group_id'], ['component_groups.id'], name=op.f('fk_trade_direction_components_component_group_id_component_groups')),
    sa.ForeignKeyConstraint(['component_template_id'], ['component_templates.id'], name=op.f('fk_trade_direction_components_component_template_id_component_templates')),
    sa.ForeignKeyConstraint(['trade_direction_id'], ['trade_directions.id'], name=op.f('fk_trade_direction_components_trade_direction_id_trade_directions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trade_direction_components')),
    sa.UniqueConstraint('trade_direction_id', 'component_template_id', name='uq_tdc_direction_template')
    )
    op.create_table('transport_assets',
    sa.Column('asset_code', sa.String(length=50), nullable=False),
    sa.Column('transport_type_id', sa.BigInteger(), nullable=False),
    sa.Column('identity', sa.String(length=128), nullable=False),
    sa.Column('identity_type', sa.String(length=64), nullable=False),
    sa.Column('registration_country_code', sa.String(length=2), nullable=True),
    sa.Column('owner_party_id', sa.BigInteger(), nullable=True),
    sa.Column('operator_party_id', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_party_id'], ['business_parties.id'], name=op.f('fk_transport_assets_operator_party_id_business_parties')),
    sa.ForeignKeyConstraint(['owner_party_id'], ['business_parties.id'], name=op.f('fk_transport_assets_owner_party_id_business_parties')),
    sa.ForeignKeyConstraint(['transport_type_id'], ['transport_types.id'], name=op.f('fk_transport_assets_transport_type_id_transport_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transport_assets')),
    sa.UniqueConstraint('asset_code', name=op.f('uq_transport_assets_asset_code')),
    sa.UniqueConstraint('transport_type_id', 'identity', name='uq_transport_assets_type_identity')
    )
    op.create_table('user_branch_assignments',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('branch_id', sa.BigInteger(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_user_branch_assignments_organization_id_organizations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_branch_assignments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'organization_id', 'branch_id', name=op.f('pk_user_branch_assignments'))
    )
    op.create_table('user_credentials',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('password_algorithm', sa.String(length=32), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('failed_attempt_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_credentials_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_credentials'))
    )
    op.create_table('user_role_assignments',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('branch_id', sa.BigInteger(), nullable=True),
    sa.Column('assigned_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], name=op.f('fk_user_role_assignments_assigned_by_user_id_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_user_role_assignments_organization_id_organizations')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_role_assignments_role_id_roles')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_role_assignments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_role_assignments'))
    )
    op.create_index(op.f('ix_user_role_assignments_user_id'), 'user_role_assignments', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=128), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions')),
    sa.UniqueConstraint('refresh_token_hash', name=op.f('uq_user_sessions_refresh_token_hash'))
    )
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('attachment_links',
    sa.Column('attachment_id', sa.BigInteger(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('attachment_role', sa.String(length=64), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachments.id'], name=op.f('fk_attachment_links_attachment_id_attachments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachment_links')),
    sa.UniqueConstraint('attachment_id', 'entity_type', 'entity_id', 'attachment_role', name='uq_attachment_links_target')
    )
    op.create_index(op.f('ix_attachment_links_attachment_id'), 'attachment_links', ['attachment_id'], unique=False)
    op.create_table('financial_accounts',
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.String(length=32), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('account_number_masked', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['chart_of_accounts.id'], name=op.f('fk_financial_accounts_account_id_chart_of_accounts')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_financial_accounts_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_accounts')),
    sa.UniqueConstraint('organization_id', 'account_id', name='uq_financial_accounts_org_account')
    )
    op.create_index(op.f('ix_financial_accounts_organization_id'), 'financial_accounts', ['organization_id'], unique=False)
    op.create_table('posting_rules',
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('document_type', sa.String(length=32), nullable=False),
    sa.Column('fee_type_id', sa.BigInteger(), nullable=True),
    sa.Column('debit_account_id', sa.BigInteger(), nullable=False),
    sa.Column('credit_account_id', sa.BigInteger(), nullable=False),
    sa.Column('tax_account_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['credit_account_id'], ['chart_of_accounts.id'], name=op.f('fk_posting_rules_credit_account_id_chart_of_accounts')),
    sa.ForeignKeyConstraint(['debit_account_id'], ['chart_of_accounts.id'], name=op.f('fk_posting_rules_debit_account_id_chart_of_accounts')),
    sa.ForeignKeyConstraint(['fee_type_id'], ['fee_types.id'], name=op.f('fk_posting_rules_fee_type_id_fee_types')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_posting_rules_organization_id_organizations')),
    sa.ForeignKeyConstraint(['tax_account_id'], ['chart_of_accounts.id'], name=op.f('fk_posting_rules_tax_account_id_chart_of_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posting_rules'))
    )
    op.create_index(op.f('ix_posting_rules_organization_id'), 'posting_rules', ['organization_id'], unique=False)
    op.create_table('quotation_revisions',
    sa.Column('quotation_id', sa.BigInteger(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('quotation_date', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('subtotal_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_quotation_revisions_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], name=op.f('fk_quotation_revisions_quotation_id_quotations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quotation_revisions')),
    sa.UniqueConstraint('quotation_id', 'revision_no', name='uq_quotation_revisions_no')
    )
    op.create_index(op.f('ix_quotation_revisions_quotation_id'), 'quotation_revisions', ['quotation_id'], unique=False)
    op.create_index(op.f('ix_quotation_revisions_status'), 'quotation_revisions', ['status'], unique=False)
    op.create_table('quotation_conversions',
    sa.Column('quotation_revision_id', sa.BigInteger(), nullable=False),
    sa.Column('service_order_id', sa.BigInteger(), nullable=False),
    sa.Column('converted_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('converted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['converted_by_user_id'], ['users.id'], name=op.f('fk_quotation_conversions_converted_by_user_id_users')),
    sa.ForeignKeyConstraint(['quotation_revision_id'], ['quotation_revisions.id'], name=op.f('fk_quotation_conversions_quotation_revision_id_quotation_revisions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quotation_conversions')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_quotation_conversions_idempotency_key')),
    sa.UniqueConstraint('quotation_revision_id', name=op.f('uq_quotation_conversions_quotation_revision_id')),
    sa.UniqueConstraint('service_order_id', name=op.f('uq_quotation_conversions_service_order_id'))
    )
    op.create_table('quotation_revision_containers',
    sa.Column('quotation_revision_id', sa.BigInteger(), nullable=False),
    sa.Column('container_type_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('gross_weight_kg', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['container_type_id'], ['container_types.id'], name=op.f('fk_quotation_revision_containers_container_type_id_container_types')),
    sa.ForeignKeyConstraint(['quotation_revision_id'], ['quotation_revisions.id'], name=op.f('fk_quotation_revision_containers_quotation_revision_id_quotation_revisions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quotation_revision_containers'))
    )
    op.create_index(op.f('ix_quotation_revision_containers_quotation_revision_id'), 'quotation_revision_containers', ['quotation_revision_id'], unique=False)
    op.create_table('quotation_revision_places',
    sa.Column('quotation_revision_id', sa.BigInteger(), nullable=False),
    sa.Column('place_id', sa.BigInteger(), nullable=True),
    sa.Column('place_role', sa.String(length=32), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('free_text', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_quotation_revision_places_place_id_places')),
    sa.ForeignKeyConstraint(['quotation_revision_id'], ['quotation_revisions.id'], name=op.f('fk_quotation_revision_places_quotation_revision_id_quotation_revisions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quotation_revision_places'))
    )
    op.create_index(op.f('ix_quotation_revision_places_quotation_revision_id'), 'quotation_revision_places', ['quotation_revision_id'], unique=False)
    op.create_table('service_orders',
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('branch_id', sa.BigInteger(), nullable=False),
    sa.Column('service_order_no', sa.String(length=50), nullable=False),
    sa.Column('quotation_revision_id', sa.BigInteger(), nullable=True),
    sa.Column('customer_party_id', sa.BigInteger(), nullable=False),
    sa.Column('trade_direction_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_service_orders_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['customer_party_id'], ['business_parties.id'], name=op.f('fk_service_orders_customer_party_id_business_parties')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_service_orders_organization_id_organizations')),
    sa.ForeignKeyConstraint(['quotation_revision_id'], ['quotation_revisions.id'], name=op.f('fk_service_orders_quotation_revision_id_quotation_revisions')),
    sa.ForeignKeyConstraint(['trade_direction_id'], ['trade_directions.id'], name=op.f('fk_service_orders_trade_direction_id_trade_directions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_orders')),
    sa.UniqueConstraint('organization_id', 'service_order_no', name='uq_service_orders_org_no')
    )
    op.create_index(op.f('ix_service_orders_organization_id'), 'service_orders', ['organization_id'], unique=False)
    op.create_index(op.f('ix_service_orders_status'), 'service_orders', ['status'], unique=False)
    op.create_table('financial_documents',
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('branch_id', sa.BigInteger(), nullable=True),
    sa.Column('document_no', sa.String(length=50), nullable=False),
    sa.Column('document_type', sa.String(length=32), nullable=False),
    sa.Column('document_date', sa.Date(), nullable=False),
    sa.Column('posting_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('party_id', sa.BigInteger(), nullable=True),
    sa.Column('service_order_id', sa.BigInteger(), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=19, scale=8), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference_number', sa.String(length=128), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('payment_method_code', sa.String(length=64), nullable=True),
    sa.Column('financial_account_id', sa.BigInteger(), nullable=True),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('subtotal_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('posted_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reversed_document_id', sa.BigInteger(), nullable=True),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_financial_documents_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['financial_account_id'], ['financial_accounts.id'], name=op.f('fk_financial_documents_financial_account_id_financial_accounts')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_financial_documents_organization_id_organizations')),
    sa.ForeignKeyConstraint(['party_id'], ['business_parties.id'], name=op.f('fk_financial_documents_party_id_business_parties')),
    sa.ForeignKeyConstraint(['posted_by_user_id'], ['users.id'], name=op.f('fk_financial_documents_posted_by_user_id_users')),
    sa.ForeignKeyConstraint(['reversed_document_id'], ['financial_documents.id'], name=op.f('fk_financial_documents_reversed_document_id_financial_documents')),
    sa.ForeignKeyConstraint(['service_order_id'], ['service_orders.id'], name=op.f('fk_financial_documents_service_order_id_service_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_documents')),
    sa.UniqueConstraint('organization_id', 'document_no', name='uq_financial_documents_org_no')
    )
    op.create_index(op.f('ix_financial_documents_document_type'), 'financial_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_financial_documents_organization_id'), 'financial_documents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_financial_documents_status'), 'financial_documents', ['status'], unique=False)
    op.create_table('quotation_revision_lines',
    sa.Column('quotation_revision_id', sa.BigInteger(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('fee_type_id', sa.BigInteger(), nullable=True),
    sa.Column('container_requirement_id', sa.BigInteger(), nullable=True),
    sa.Column('service_description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_code', sa.String(length=32), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('discount_rate', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('line_subtotal', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('line_discount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('line_tax', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['container_requirement_id'], ['quotation_revision_containers.id'], name=op.f('fk_quotation_revision_lines_container_requirement_id_quotation_revision_containers')),
    sa.ForeignKeyConstraint(['fee_type_id'], ['fee_types.id'], name=op.f('fk_quotation_revision_lines_fee_type_id_fee_types')),
    sa.ForeignKeyConstraint(['quotation_revision_id'], ['quotation_revisions.id'], name=op.f('fk_quotation_revision_lines_quotation_revision_id_quotation_revisions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quotation_revision_lines')),
    sa.UniqueConstraint('quotation_revision_id', 'line_no', name='uq_quotation_revision_lines_no')
    )
    op.create_index(op.f('ix_quotation_revision_lines_quotation_revision_id'), 'quotation_revision_lines', ['quotation_revision_id'], unique=False)
    op.create_table('service_order_charges',
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('branch_id', sa.BigInteger(), nullable=False),
    sa.Column('service_order_id', sa.BigInteger(), nullable=False),
    sa.Column('charge_no', sa.String(length=50), nullable=False),
    sa.Column('document_type', sa.String(length=32), nullable=False),
    sa.Column('document_date', sa.Date(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('subtotal_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_service_order_charges_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_service_order_charges_organization_id_organizations')),
    sa.ForeignKeyConstraint(['service_order_id'], ['service_orders.id'], name=op.f('fk_service_order_charges_service_order_id_service_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_order_charges')),
    sa.UniqueConstraint('organization_id', 'charge_no', name='uq_service_order_charges_org_no')
    )
    op.create_index(op.f('ix_service_order_charges_organization_id'), 'service_order_charges', ['organization_id'], unique=False)
    op.create_index(op.f('ix_service_order_charges_service_order_id'), 'service_order_charges', ['service_order_id'], unique=False)
    op.create_index(op.f('ix_service_order_charges_status'), 'service_order_charges', ['status'], unique=False)
    op.create_table('service_order_components',
    sa.Column('service_order_id', sa.BigInteger(), nullable=False),
    sa.Column('trade_direction_component_id', sa.BigInteger(), nullable=True),
    sa.Column('component_group_id', sa.BigInteger(), nullable=True),
    sa.Column('component_template_id', sa.BigInteger(), nullable=False),
    sa.Column('template_code', sa.String(length=64), nullable=False),
    sa.Column('template_version', sa.Integer(), nullable=False),
    sa.Column('component_status', sa.String(length=20), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_repeatable', sa.Boolean(), nullable=False),
    sa.Column('instance_mode', sa.String(length=20), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('completed_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['completed_by_user_id'], ['users.id'], name=op.f('fk_service_order_components_completed_by_user_id_users')),
    sa.ForeignKeyConstraint(['component_group_id'], ['component_groups.id'], name=op.f('fk_service_order_components_component_group_id_component_groups')),
    sa.ForeignKeyConstraint(['component_template_id'], ['component_templates.id'], name=op.f('fk_service_order_components_component_template_id_component_templates')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_service_order_components_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['service_order_id'], ['service_orders.id'], name=op.f('fk_service_order_components_service_order_id_service_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trade_direction_component_id'], ['trade_direction_components.id'], name=op.f('fk_service_order_components_trade_direction_component_id_trade_direction_components')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_order_components'))
    )
    op.create_index(op.f('ix_service_order_components_component_status'), 'service_order_components', ['component_status'], unique=False)
    op.create_index(op.f('ix_service_order_components_service_order_id'), 'service_order_components', ['service_order_id'], unique=False)
    op.create_table('service_order_container_requirements',
    sa.Column('service_order_id', sa.BigInteger(), nullable=False),
    sa.Column('source_quotation_container_id', sa.BigInteger(), nullable=True),
    sa.Column('container_type_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('gross_weight_kg', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['container_type_id'], ['container_types.id'], name=op.f('fk_service_order_container_requirements_container_type_id_container_types')),
    sa.ForeignKeyConstraint(['service_order_id'], ['service_orders.id'], name=op.f('fk_service_order_container_requirements_service_order_id_service_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_quotation_container_id'], ['quotation_revision_containers.id'], name=op.f('fk_service_order_container_requirements_source_quotation_container_id_quotation_revision_containers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_order_container_requirements'))
    )
    op.create_index(op.f('ix_service_order_container_requirements_service_order_id'), 'service_order_container_requirements', ['service_order_id'], unique=False)
    op.create_table('service_order_milestones',
    sa.Column('service_order_id', sa.BigInteger(), nullable=False),
    sa.Column('milestone_code', sa.String(length=64), nullable=False),
    sa.Column('milestone_name', sa.String(length=255), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('planned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['service_order_id'], ['service_orders.id'], name=op.f('fk_service_order_milestones_service_order_id_service_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_order_milestones'))
    )
    op.create_index(op.f('ix_service_order_milestones_service_order_id'), 'service_order_milestones', ['service_order_id'], unique=False)
    op.create_table('service_order_movements',
    sa.Column('service_order_id', sa.BigInteger(), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('transport_type_id', sa.BigInteger(), nullable=True),
    sa.Column('transport_asset_id', sa.BigInteger(), nullable=True),
    sa.Column('origin_place_id', sa.BigInteger(), nullable=True),
    sa.Column('destination_place_id', sa.BigInteger(), nullable=True),
    sa.Column('planned_departure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_departure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_place_id'], ['places.id'], name=op.f('fk_service_order_movements_destination_place_id_places')),
    sa.ForeignKeyConstraint(['origin_place_id'], ['places.id'], name=op.f('fk_service_order_movements_origin_place_id_places')),
    sa.ForeignKeyConstraint(['service_order_id'], ['service_orders.id'], name=op.f('fk_service_order_movements_service_order_id_service_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transport_asset_id'], ['transport_assets.id'], name=op.f('fk_service_order_movements_transport_asset_id_transport_assets')),
    sa.ForeignKeyConstraint(['transport_type_id'], ['transport_types.id'], name=op.f('fk_service_order_movements_transport_type_id_transport_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_order_movements'))
    )
    op.create_index(op.f('ix_service_order_movements_service_order_id'), 'service_order_movements', ['service_order_id'], unique=False)
    op.create_table('service_order_places',
    sa.Column('service_order_id', sa.BigInteger(), nullable=False),
    sa.Column('place_id', sa.BigInteger(), nullable=True),
    sa.Column('place_role', sa.String(length=32), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('free_text', sa.Text(), nullable=True),
    sa.Column('is_actual', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_service_order_places_place_id_places')),
    sa.ForeignKeyConstraint(['service_order_id'], ['service_orders.id'], name=op.f('fk_service_order_places_service_order_id_service_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_order_places'))
    )
    op.create_index(op.f('ix_service_order_places_service_order_id'), 'service_order_places', ['service_order_id'], unique=False)
    op.create_table('service_order_pricing',
    sa.Column('service_order_id', sa.BigInteger(), nullable=False),
    sa.Column('subtotal_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['service_order_id'], ['service_orders.id'], name=op.f('fk_service_order_pricing_service_order_id_service_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_order_pricing')),
    sa.UniqueConstraint('service_order_id', name=op.f('uq_service_order_pricing_service_order_id'))
    )
    op.create_table('financial_document_allocations',
    sa.Column('payment_document_id', sa.BigInteger(), nullable=False),
    sa.Column('target_document_id', sa.BigInteger(), nullable=False),
    sa.Column('allocated_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('allocated_currency_code', sa.String(length=3), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=19, scale=8), nullable=False),
    sa.Column('allocated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_financial_document_allocations_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['payment_document_id'], ['financial_documents.id'], name=op.f('fk_financial_document_allocations_payment_document_id_financial_documents')),
    sa.ForeignKeyConstraint(['target_document_id'], ['financial_documents.id'], name=op.f('fk_financial_document_allocations_target_document_id_financial_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_document_allocations')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_financial_document_allocations_idempotency_key'))
    )
    op.create_index(op.f('ix_financial_document_allocations_payment_document_id'), 'financial_document_allocations', ['payment_document_id'], unique=False)
    op.create_index(op.f('ix_financial_document_allocations_target_document_id'), 'financial_document_allocations', ['target_document_id'], unique=False)
    op.create_table('financial_document_sources',
    sa.Column('financial_document_id', sa.BigInteger(), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('relationship_type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['financial_document_id'], ['financial_documents.id'], name=op.f('fk_financial_document_sources_financial_document_id_financial_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_document_sources')),
    sa.UniqueConstraint('financial_document_id', 'source_type', 'source_id', 'relationship_type', name='uq_fin_doc_sources')
    )
    op.create_index(op.f('ix_financial_document_sources_financial_document_id'), 'financial_document_sources', ['financial_document_id'], unique=False)
    op.create_table('journal_entries',
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('branch_id', sa.BigInteger(), nullable=True),
    sa.Column('entry_no', sa.String(length=50), nullable=False),
    sa.Column('entry_type', sa.String(length=64), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('posting_date', sa.Date(), nullable=False),
    sa.Column('accounting_period_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_document_id', sa.BigInteger(), nullable=True),
    sa.Column('reversal_of_journal_entry_id', sa.BigInteger(), nullable=True),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('posted_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('debit_total', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('credit_total', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accounting_period_id'], ['accounting_periods.id'], name=op.f('fk_journal_entries_accounting_period_id_accounting_periods')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_journal_entries_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_journal_entries_organization_id_organizations')),
    sa.ForeignKeyConstraint(['posted_by_user_id'], ['users.id'], name=op.f('fk_journal_entries_posted_by_user_id_users')),
    sa.ForeignKeyConstraint(['reversal_of_journal_entry_id'], ['journal_entries.id'], name=op.f('fk_journal_entries_reversal_of_journal_entry_id_journal_entries')),
    sa.ForeignKeyConstraint(['source_document_id'], ['financial_documents.id'], name=op.f('fk_journal_entries_source_document_id_financial_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journal_entries')),
    sa.UniqueConstraint('organization_id', 'entry_no', name='uq_journal_entries_org_no')
    )
    op.create_index(op.f('ix_journal_entries_organization_id'), 'journal_entries', ['organization_id'], unique=False)
    op.create_index(op.f('ix_journal_entries_status'), 'journal_entries', ['status'], unique=False)
    op.create_table('service_component_values',
    sa.Column('component_id', sa.BigInteger(), nullable=False),
    sa.Column('template_attribute_id', sa.BigInteger(), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_number', sa.Numeric(precision=19, scale=6), nullable=True),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('value_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('value_boolean', sa.Boolean(), nullable=True),
    sa.Column('value_reference_type', sa.String(length=64), nullable=True),
    sa.Column('value_reference_id', sa.BigInteger(), nullable=True),
    sa.Column('value_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['service_order_components.id'], name=op.f('fk_service_component_values_component_id_service_order_components'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_attribute_id'], ['template_attributes.id'], name=op.f('fk_service_component_values_template_attribute_id_template_attributes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_component_values')),
    sa.UniqueConstraint('component_id', 'template_attribute_id', name='uq_service_component_values_attr')
    )
    op.create_index(op.f('ix_service_component_values_component_id'), 'service_component_values', ['component_id'], unique=False)
    op.create_table('service_order_containers',
    sa.Column('service_order_id', sa.BigInteger(), nullable=False),
    sa.Column('container_requirement_id', sa.BigInteger(), nullable=True),
    sa.Column('container_type_id', sa.BigInteger(), nullable=False),
    sa.Column('container_number', sa.String(length=32), nullable=False),
    sa.Column('seal_serial', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('net_weight_kg', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('gross_weight_kg', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('pickup_date', sa.Date(), nullable=True),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['container_requirement_id'], ['service_order_container_requirements.id'], name=op.f('fk_service_order_containers_container_requirement_id_service_order_container_requirements')),
    sa.ForeignKeyConstraint(['container_type_id'], ['container_types.id'], name=op.f('fk_service_order_containers_container_type_id_container_types')),
    sa.ForeignKeyConstraint(['service_order_id'], ['service_orders.id'], name=op.f('fk_service_order_containers_service_order_id_service_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_order_containers')),
    sa.UniqueConstraint('container_number', name='uq_service_order_containers_number')
    )
    op.create_index(op.f('ix_service_order_containers_service_order_id'), 'service_order_containers', ['service_order_id'], unique=False)
    op.create_table('service_order_pricing_lines',
    sa.Column('service_order_pricing_id', sa.BigInteger(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('source_quotation_line_id', sa.BigInteger(), nullable=True),
    sa.Column('fee_type_id', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_code', sa.String(length=32), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('discount_rate', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['fee_type_id'], ['fee_types.id'], name=op.f('fk_service_order_pricing_lines_fee_type_id_fee_types')),
    sa.ForeignKeyConstraint(['service_order_pricing_id'], ['service_order_pricing.id'], name=op.f('fk_service_order_pricing_lines_service_order_pricing_id_service_order_pricing'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_quotation_line_id'], ['quotation_revision_lines.id'], name=op.f('fk_service_order_pricing_lines_source_quotation_line_id_quotation_revision_lines')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_order_pricing_lines')),
    sa.UniqueConstraint('service_order_pricing_id', 'line_no', name='uq_so_pricing_lines_no')
    )
    op.create_index(op.f('ix_service_order_pricing_lines_service_order_pricing_id'), 'service_order_pricing_lines', ['service_order_pricing_id'], unique=False)
    op.create_table('financial_document_lines',
    sa.Column('financial_document_id', sa.BigInteger(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('fee_type_id', sa.BigInteger(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_code', sa.String(length=32), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('line_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('service_order_id', sa.BigInteger(), nullable=True),
    sa.Column('service_order_container_id', sa.BigInteger(), nullable=True),
    sa.Column('account_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['chart_of_accounts.id'], name=op.f('fk_financial_document_lines_account_id_chart_of_accounts')),
    sa.ForeignKeyConstraint(['fee_type_id'], ['fee_types.id'], name=op.f('fk_financial_document_lines_fee_type_id_fee_types')),
    sa.ForeignKeyConstraint(['financial_document_id'], ['financial_documents.id'], name=op.f('fk_financial_document_lines_financial_document_id_financial_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_order_container_id'], ['service_order_containers.id'], name=op.f('fk_financial_document_lines_service_order_container_id_service_order_containers')),
    sa.ForeignKeyConstraint(['service_order_id'], ['service_orders.id'], name=op.f('fk_financial_document_lines_service_order_id_service_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_document_lines')),
    sa.UniqueConstraint('financial_document_id', 'line_no', name='uq_financial_document_lines_no')
    )
    op.create_index(op.f('ix_financial_document_lines_financial_document_id'), 'financial_document_lines', ['financial_document_id'], unique=False)
    op.create_table('financial_document_postings',
    sa.Column('financial_document_id', sa.BigInteger(), nullable=False),
    sa.Column('journal_entry_id', sa.BigInteger(), nullable=False),
    sa.Column('posting_role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['financial_document_id'], ['financial_documents.id'], name=op.f('fk_financial_document_postings_financial_document_id_financial_documents')),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], name=op.f('fk_financial_document_postings_journal_entry_id_journal_entries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_document_postings')),
    sa.UniqueConstraint('financial_document_id', 'journal_entry_id', name='uq_fin_doc_postings')
    )
    op.create_table('journal_entry_lines',
    sa.Column('journal_entry_id', sa.BigInteger(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('party_id', sa.BigInteger(), nullable=True),
    sa.Column('service_order_id', sa.BigInteger(), nullable=True),
    sa.Column('financial_document_id', sa.BigInteger(), nullable=True),
    sa.Column('branch_id', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('debit_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('credit_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=19, scale=8), nullable=False),
    sa.Column('base_debit_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('base_credit_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['chart_of_accounts.id'], name=op.f('fk_journal_entry_lines_account_id_chart_of_accounts')),
    sa.ForeignKeyConstraint(['financial_document_id'], ['financial_documents.id'], name=op.f('fk_journal_entry_lines_financial_document_id_financial_documents')),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], name=op.f('fk_journal_entry_lines_journal_entry_id_journal_entries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['party_id'], ['business_parties.id'], name=op.f('fk_journal_entry_lines_party_id_business_parties')),
    sa.ForeignKeyConstraint(['service_order_id'], ['service_orders.id'], name=op.f('fk_journal_entry_lines_service_order_id_service_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journal_entry_lines')),
    sa.UniqueConstraint('journal_entry_id', 'line_no', name='uq_journal_entry_lines_no')
    )
    op.create_index(op.f('ix_journal_entry_lines_account_id'), 'journal_entry_lines', ['account_id'], unique=False)
    op.create_index(op.f('ix_journal_entry_lines_journal_entry_id'), 'journal_entry_lines', ['journal_entry_id'], unique=False)
    op.create_table('service_order_charge_lines',
    sa.Column('service_order_charge_id', sa.BigInteger(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('fee_type_id', sa.BigInteger(), nullable=True),
    sa.Column('service_order_container_id', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_code', sa.String(length=32), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('line_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['fee_type_id'], ['fee_types.id'], name=op.f('fk_service_order_charge_lines_fee_type_id_fee_types')),
    sa.ForeignKeyConstraint(['service_order_charge_id'], ['service_order_charges.id'], name=op.f('fk_service_order_charge_lines_service_order_charge_id_service_order_charges'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_order_container_id'], ['service_order_containers.id'], name=op.f('fk_service_order_charge_lines_service_order_container_id_service_order_containers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_order_charge_lines')),
    sa.UniqueConstraint('service_order_charge_id', 'line_no', name='uq_service_order_charge_lines_no')
    )
    op.create_index(op.f('ix_service_order_charge_lines_service_order_charge_id'), 'service_order_charge_lines', ['service_order_charge_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_order_charge_lines_service_order_charge_id'), table_name='service_order_charge_lines')
    op.drop_table('service_order_charge_lines')
    op.drop_index(op.f('ix_journal_entry_lines_journal_entry_id'), table_name='journal_entry_lines')
    op.drop_index(op.f('ix_journal_entry_lines_account_id'), table_name='journal_entry_lines')
    op.drop_table('journal_entry_lines')
    op.drop_table('financial_document_postings')
    op.drop_index(op.f('ix_financial_document_lines_financial_document_id'), table_name='financial_document_lines')
    op.drop_table('financial_document_lines')
    op.drop_index(op.f('ix_service_order_pricing_lines_service_order_pricing_id'), table_name='service_order_pricing_lines')
    op.drop_table('service_order_pricing_lines')
    op.drop_index(op.f('ix_service_order_containers_service_order_id'), table_name='service_order_containers')
    op.drop_table('service_order_containers')
    op.drop_index(op.f('ix_service_component_values_component_id'), table_name='service_component_values')
    op.drop_table('service_component_values')
    op.drop_index(op.f('ix_journal_entries_status'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_organization_id'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index(op.f('ix_financial_document_sources_financial_document_id'), table_name='financial_document_sources')
    op.drop_table('financial_document_sources')
    op.drop_index(op.f('ix_financial_document_allocations_target_document_id'), table_name='financial_document_allocations')
    op.drop_index(op.f('ix_financial_document_allocations_payment_document_id'), table_name='financial_document_allocations')
    op.drop_table('financial_document_allocations')
    op.drop_table('service_order_pricing')
    op.drop_index(op.f('ix_service_order_places_service_order_id'), table_name='service_order_places')
    op.drop_table('service_order_places')
    op.drop_index(op.f('ix_service_order_movements_service_order_id'), table_name='service_order_movements')
    op.drop_table('service_order_movements')
    op.drop_index(op.f('ix_service_order_milestones_service_order_id'), table_name='service_order_milestones')
    op.drop_table('service_order_milestones')
    op.drop_index(op.f('ix_service_order_container_requirements_service_order_id'), table_name='service_order_container_requirements')
    op.drop_table('service_order_container_requirements')
    op.drop_index(op.f('ix_service_order_components_service_order_id'), table_name='service_order_components')
    op.drop_index(op.f('ix_service_order_components_component_status'), table_name='service_order_components')
    op.drop_table('service_order_components')
    op.drop_index(op.f('ix_service_order_charges_status'), table_name='service_order_charges')
    op.drop_index(op.f('ix_service_order_charges_service_order_id'), table_name='service_order_charges')
    op.drop_index(op.f('ix_service_order_charges_organization_id'), table_name='service_order_charges')
    op.drop_table('service_order_charges')
    op.drop_index(op.f('ix_quotation_revision_lines_quotation_revision_id'), table_name='quotation_revision_lines')
    op.drop_table('quotation_revision_lines')
    op.drop_index(op.f('ix_financial_documents_status'), table_name='financial_documents')
    op.drop_index(op.f('ix_financial_documents_organization_id'), table_name='financial_documents')
    op.drop_index(op.f('ix_financial_documents_document_type'), table_name='financial_documents')
    op.drop_table('financial_documents')
    op.drop_index(op.f('ix_service_orders_status'), table_name='service_orders')
    op.drop_index(op.f('ix_service_orders_organization_id'), table_name='service_orders')
    op.drop_table('service_orders')
    op.drop_index(op.f('ix_quotation_revision_places_quotation_revision_id'), table_name='quotation_revision_places')
    op.drop_table('quotation_revision_places')
    op.drop_index(op.f('ix_quotation_revision_containers_quotation_revision_id'), table_name='quotation_revision_containers')
    op.drop_table('quotation_revision_containers')
    op.drop_table('quotation_conversions')
    op.drop_index(op.f('ix_quotation_revisions_status'), table_name='quotation_revisions')
    op.drop_index(op.f('ix_quotation_revisions_quotation_id'), table_name='quotation_revisions')
    op.drop_table('quotation_revisions')
    op.drop_index(op.f('ix_posting_rules_organization_id'), table_name='posting_rules')
    op.drop_table('posting_rules')
    op.drop_index(op.f('ix_financial_accounts_organization_id'), table_name='financial_accounts')
    op.drop_table('financial_accounts')
    op.drop_index(op.f('ix_attachment_links_attachment_id'), table_name='attachment_links')
    op.drop_table('attachment_links')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_user_role_assignments_user_id'), table_name='user_role_assignments')
    op.drop_table('user_role_assignments')
    op.drop_table('user_credentials')
    op.drop_table('user_branch_assignments')
    op.drop_table('transport_assets')
    op.drop_table('trade_direction_components')
    op.drop_table('template_attributes')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_quotations_status'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_organization_id'), table_name='quotations')
    op.drop_table('quotations')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_table('party_roles')
    op.drop_table('party_places')
    op.drop_index(op.f('ix_module_records_organization_id'), table_name='module_records')
    op.drop_index(op.f('ix_module_records_collection'), table_name='module_records')
    op.drop_index(op.f('ix_module_records_branch_id'), table_name='module_records')
    op.drop_table('module_records')
    op.drop_index(op.f('ix_document_sequences_organization_id'), table_name='document_sequences')
    op.drop_table('document_sequences')
    op.drop_table('customer_customs_accounts')
    op.drop_index(op.f('ix_chart_of_accounts_organization_id'), table_name='chart_of_accounts')
    op.drop_table('chart_of_accounts')
    op.drop_index(op.f('ix_branches_organization_id'), table_name='branches')
    op.drop_table('branches')
    op.drop_index(op.f('ix_audit_events_organization_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_attachments_organization_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_accounting_periods_status'), table_name='accounting_periods')
    op.drop_index(op.f('ix_accounting_periods_organization_id'), table_name='accounting_periods')
    op.drop_table('accounting_periods')
    op.drop_table('users')
    op.drop_table('transport_types')
    op.drop_table('trade_directions')
    op.drop_table('roles')
    op.drop_table('places')
    op.drop_table('permissions')
    op.drop_table('organizations')
    op.drop_table('fee_types')
    op.drop_table('container_types')
    op.drop_table('component_templates')
    op.drop_table('component_groups')
    op.drop_table('business_parties')
    # ### end Alembic commands ###
