"""service order dynamic tab configs and rows

Revision ID: 6e862ce04e46
Revises: 140cae56fc24
Create Date: 2026-09-15 14:07:59.429299

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '6e862ce04e46'
down_revision: str | None = '140cae56fc24'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_order_tab_configs',
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_km', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('allow_multiple_rows', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_service_order_tab_configs_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_order_tab_configs')),
    sa.UniqueConstraint('organization_id', 'code', name='uq_so_tab_configs_org_code')
    )
    op.create_index(op.f('ix_service_order_tab_configs_organization_id'), 'service_order_tab_configs', ['organization_id'], unique=False)
    op.create_table('service_order_column_configs',
    sa.Column('tab_id', sa.BigInteger(), nullable=False),
    sa.Column('field_key', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('label_km', sa.String(length=255), nullable=True),
    sa.Column('field_type', sa.String(length=32), nullable=False),
    sa.Column('reference_type', sa.String(length=32), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('show_in_summary', sa.Boolean(), nullable=False),
    sa.Column('width', sa.String(length=16), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('default_value', sa.String(length=255), nullable=True),
    sa.Column('placeholder', sa.String(length=255), nullable=True),
    sa.Column('validation_rules', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('options', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tab_id'], ['service_order_tab_configs.id'], name=op.f('fk_service_order_column_configs_tab_id_service_order_tab_configs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_order_column_configs')),
    sa.UniqueConstraint('tab_id', 'field_key', name='uq_so_column_configs_tab_key')
    )
    op.create_index(op.f('ix_service_order_column_configs_tab_id'), 'service_order_column_configs', ['tab_id'], unique=False)
    op.create_table('service_order_tab_rows',
    sa.Column('service_order_id', sa.BigInteger(), nullable=False),
    sa.Column('tab_config_id', sa.BigInteger(), nullable=False),
    sa.Column('tab_code', sa.String(length=64), nullable=False),
    sa.Column('row_no', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('values', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_service_order_tab_rows_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['service_order_id'], ['service_orders.id'], name=op.f('fk_service_order_tab_rows_service_order_id_service_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tab_config_id'], ['service_order_tab_configs.id'], name=op.f('fk_service_order_tab_rows_tab_config_id_service_order_tab_configs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_service_order_tab_rows_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_order_tab_rows'))
    )
    op.create_index(op.f('ix_service_order_tab_rows_service_order_id'), 'service_order_tab_rows', ['service_order_id'], unique=False)
    op.create_index(op.f('ix_service_order_tab_rows_tab_config_id'), 'service_order_tab_rows', ['tab_config_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_order_tab_rows_tab_config_id'), table_name='service_order_tab_rows')
    op.drop_index(op.f('ix_service_order_tab_rows_service_order_id'), table_name='service_order_tab_rows')
    op.drop_table('service_order_tab_rows')
    op.drop_index(op.f('ix_service_order_column_configs_tab_id'), table_name='service_order_column_configs')
    op.drop_table('service_order_column_configs')
    op.drop_index(op.f('ix_service_order_tab_configs_organization_id'), table_name='service_order_tab_configs')
    op.drop_table('service_order_tab_configs')
    # ### end Alembic commands ###
