"""ERP-style permission catalog and default role → permission mapping.

Permission codes use ``module.action``. Source permissions mirror the frontend
``SOURCE_PERMISSIONS`` contract; the extra page-level keys keep the existing
frontend navigation and configuration screens working.
"""

from __future__ import annotations

# --- Source (API) permissions -------------------------------------------------
SOURCE_PERMISSIONS: tuple[tuple[str, str, str], ...] = (
    ("organization.read", "organization", "read"),
    ("organization.update", "organization", "update"),
    ("branch.read", "branch", "read"),
    ("branch.manage", "branch", "manage"),
    ("user.read", "user", "read"),
    ("user.manage", "user", "manage"),
    ("role.read", "role", "read"),
    ("role.manage", "role", "manage"),
    ("quotation.read", "quotation", "read"),
    ("quotation.create", "quotation", "create"),
    ("quotation.update_draft", "quotation", "update_draft"),
    ("quotation.send", "quotation", "send"),
    ("quotation.accept", "quotation", "accept"),
    ("quotation.convert", "quotation", "convert"),
    ("service_order.read", "service_order", "read"),
    ("service_order.create", "service_order", "create"),
    ("service_order.update", "service_order", "update"),
    ("service_order.complete", "service_order", "complete"),
    ("service_order_config.view", "service_order_config", "view"),
    ("service_order_config.create", "service_order_config", "create"),
    ("service_order_config.update", "service_order_config", "update"),
    ("service_order_config.delete", "service_order_config", "delete"),
    ("service_charge.create", "service_charge", "create"),
    ("service_charge.issue", "service_charge", "issue"),
    ("service_charge.convert_to_invoice", "service_charge", "convert_to_invoice"),
    ("financial_document.read", "financial_document", "read"),
    ("financial_document.create", "financial_document", "create"),
    ("financial_document.update_draft", "financial_document", "update_draft"),
    ("financial_document.post", "financial_document", "post"),
    ("financial_document.reverse", "financial_document", "reverse"),
    ("financial_document.allocate", "financial_document", "allocate"),
    ("journal_entry.read", "journal_entry", "read"),
    ("journal_entry.create", "journal_entry", "create"),
    ("journal_entry.post", "journal_entry", "post"),
    ("accounting_period.read", "accounting_period", "read"),
    ("accounting_period.close", "accounting_period", "close"),
    ("chart_of_accounts.manage", "chart_of_accounts", "manage"),
    ("customs_credential.retrieve", "customs_credential", "retrieve"),
    ("attachment.read", "attachment", "read"),
    ("attachment.upload", "attachment", "upload"),
    ("attachment.delete", "attachment", "delete"),
    ("audit_log.read", "audit_log", "read"),
    ("report.read", "report", "read"),
)

# --- Page / configuration permissions (frontend navigation) -------------------
PAGE_PERMISSIONS: tuple[tuple[str, str, str], ...] = (
    ("master.reference.view", "master_data", "view"),
    ("master.reference.manage", "master_data", "manage"),
    ("configuration.manage", "configuration", "manage"),
    ("configuration.configure", "configuration", "configure"),
    ("admin.user_manage", "admin", "user_manage"),
    ("admin.role_manage", "admin", "role_manage"),
    ("admin.organization_manage", "admin", "organization_manage"),
    ("settings.manage", "settings", "manage"),
    ("finance.view", "finance", "view"),
    ("report.export", "report", "export"),
)

PERMISSION_CATALOG: tuple[tuple[str, str, str], ...] = SOURCE_PERMISSIONS + PAGE_PERMISSIONS

ALL_PERMISSION_CODES = tuple(code for code, _, _ in PERMISSION_CATALOG)


def permission_name(code: str) -> str:
    return code.replace(".", " ").replace("_", " ").title()


ALL_SOURCE = tuple(code for code, _, _ in SOURCE_PERMISSIONS)
ALL_PAGES = ("ALL_PAGES",)


ROLE_DEFINITIONS: dict[str, dict[str, object]] = {
    "PLATFORM_ADMIN": {
        "name": "Platform Administrator",
        "description": "Full platform administration",
        "permissions": tuple(ALL_PERMISSION_CODES),
    },
    "ORGANIZATION_ADMIN": {
        "name": "Organization Administrator",
        "description": "Organization and branch administration",
        "permissions": (
            "organization.read",
            "organization.update",
            "branch.read",
            "branch.manage",
            "user.read",
            "user.manage",
            "role.read",
            "role.manage",
            "quotation.read",
            "quotation.create",
            "quotation.update_draft",
            "quotation.send",
            "quotation.accept",
            "quotation.convert",
            "service_order.read",
            "service_order.create",
            "service_order.update",
            "service_order.complete",
            "service_order_config.view",
            "service_order_config.create",
            "service_order_config.update",
            "service_order_config.delete",
            "service_charge.create",
            "service_charge.issue",
            "service_charge.convert_to_invoice",
            "financial_document.read",
            "financial_document.create",
            "financial_document.update_draft",
            "financial_document.post",
            "financial_document.reverse",
            "financial_document.allocate",
            "journal_entry.read",
            "journal_entry.create",
            "journal_entry.post",
            "accounting_period.read",
            "accounting_period.close",
            "chart_of_accounts.manage",
            "attachment.read",
            "attachment.upload",
            "attachment.delete",
            "audit_log.read",
            "report.read",
            "master.reference.view",
            "master.reference.manage",
            "configuration.manage",
            "admin.user_manage",
            "admin.role_manage",
            "admin.organization_manage",
            "settings.manage",
        ),
    },
    "BRANCH_MANAGER": {
        "name": "Branch Manager",
        "description": "Branch operations and review",
        "permissions": (
            "organization.read",
            "branch.read",
            "user.read",
            "role.read",
            "quotation.read",
            "quotation.create",
            "quotation.update_draft",
            "quotation.send",
            "quotation.accept",
            "quotation.convert",
            "service_order.read",
            "service_order.create",
            "service_order.update",
            "service_order.complete",
            "service_order_config.view",
            "service_order_config.update",
            "service_charge.create",
            "service_charge.issue",
            "financial_document.read",
            "attachment.read",
            "attachment.upload",
            "audit_log.read",
            "report.read",
            "master.reference.view",
            "master.reference.manage",
        ),
    },
    "SALES_OFFICER": {
        "name": "Sales Officer",
        "description": "Quotation and commercial work",
        "permissions": (
            "organization.read",
            "branch.read",
            "quotation.read",
            "quotation.create",
            "quotation.update_draft",
            "quotation.send",
            "quotation.accept",
            "quotation.convert",
            "service_order.read",
            "service_charge.create",
            "service_charge.issue",
            "attachment.read",
            "attachment.upload",
            "report.read",
            "master.reference.view",
        ),
    },
    "OPERATIONS_OFFICER": {
        "name": "Operations Officer",
        "description": "Service-order operations",
        "permissions": (
            "organization.read",
            "branch.read",
            "quotation.read",
            "quotation.convert",
            "service_order.read",
            "service_order.create",
            "service_order.update",
            "service_order.complete",
            "service_charge.create",
            "service_charge.issue",
            "attachment.read",
            "attachment.upload",
            "report.read",
            "master.reference.view",
        ),
    },
    "FINANCE_OFFICER": {
        "name": "Finance Officer",
        "description": "Financial drafts, payments, and allocations",
        "permissions": (
            "organization.read",
            "branch.read",
            "service_order.read",
            "service_charge.create",
            "service_charge.issue",
            "service_charge.convert_to_invoice",
            "financial_document.read",
            "financial_document.create",
            "financial_document.update_draft",
            "financial_document.post",
            "financial_document.allocate",
            "journal_entry.read",
            "journal_entry.create",
            "journal_entry.post",
            "accounting_period.read",
            "attachment.read",
            "attachment.upload",
            "report.read",
            "master.reference.view",
            "finance.view",
        ),
    },
    "FINANCE_MANAGER": {
        "name": "Finance Manager",
        "description": "Posting, periods, journals, and reversals",
        "permissions": (
            "organization.read",
            "branch.read",
            "financial_document.read",
            "financial_document.create",
            "financial_document.update_draft",
            "financial_document.post",
            "financial_document.reverse",
            "financial_document.allocate",
            "journal_entry.read",
            "journal_entry.create",
            "journal_entry.post",
            "accounting_period.read",
            "accounting_period.close",
            "chart_of_accounts.manage",
            "audit_log.read",
            "attachment.read",
            "report.read",
            "master.reference.view",
            "finance.view",
            "report.export",
        ),
    },
    "AUDITOR": {
        "name": "Auditor",
        "description": "Read-only review",
        "permissions": (
            "organization.read",
            "branch.read",
            "user.read",
            "role.read",
            "quotation.read",
            "service_order.read",
            "financial_document.read",
            "journal_entry.read",
            "accounting_period.read",
            "attachment.read",
            "audit_log.read",
            "report.read",
            "master.reference.view",
            "finance.view",
        ),
    },
}
